e1ap: remove zero list initializer from vector
could be the reason for issues with some compilers, e.g.:

FAILED: lib/cu_cp/CMakeFiles/srsran_cu_cp.dir/routines/pdu_session_routine_helpers.cpp.o
ccache /usr/bin/g++ -DASSERTS_ENABLED -DHAVE_AVX -DHAVE_AVX2 -DHAVE_SSE -DPARANOID_ASSERTS_ENABLED -I../include -I../external/fmt/include -I../external -Wall -Werror -Wnon-virtual-dtor -Wsuggest-override -Wshadow -march=native -mfma -DHAVE_FMA -O3 -DNDEBUG -fno-trapping-math -fno-math-errno -DBUILD_TYPE_RELEASE -std=gnu++14 -MD -MT lib/cu_cp/CMakeFiles/srsran_cu_cp.dir/routines/pdu_session_routine_helpers.cpp.o -MF lib/cu_cp/CMakeFiles/srsran_cu_cp.dir/routines/pdu_session_routine_helpers.cpp.o.d -o lib/cu_cp/CMakeFiles/srsran_cu_cp.dir/routines/pdu_session_routine_helpers.cpp.o -c ../lib/cu_cp/routines/pdu_session_routine_helpers.cpp
In file included from /opt/rh/gcc-toolset-12/root/usr/include/c++/12/string:53,
                 from /opt/rh/gcc-toolset-12/root/usr/include/c++/12/stdexcept:39,
                 from ../external/fmt/include/fmt/format.h:42,
                 from ../include/srsran/adt/span.h:13,
                 from ../include/srsran/adt/detail/byte_buffer_segment.h:13,
                 from ../include/srsran/adt/byte_buffer.h:13,
                 from ../include/srsran/cu_cp/cu_cp_types.h:13,
                 from ../lib/cu_cp/routines/pdu_session_routine_helpers.h:13,
                 from ../lib/cu_cp/routines/pdu_session_routine_helpers.cpp:11:
In member function 'void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_dispose() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]',
    inlined from 'std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::~basic_string() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/basic_string.h:794:19,
    inlined from 'constexpr void srsran::detail::base_optional_storage<T>::destroy_() [with T = std::__cxx11::basic_string<char>]' at ../include/srsran/adt/optional.h:103:26,
    inlined from 'constexpr void srsran::detail::base_optional_storage<T>::reset_() [with T = std::__cxx11::basic_string<char>]' at ../include/srsran/adt/optional.h:109:15,
    inlined from 'constexpr void srsran::detail::base_optional_storage<T>::reset_() [with T = std::__cxx11::basic_string<char>]' at ../include/srsran/adt/optional.h:106:18,
    inlined from 'srsran::detail::optional_storage<T, false, TrivialCopy, TrivialMove>::~optional_storage() [with T = std::__cxx11::basic_string<char>; bool TrivialCopy = false; bool TrivialMove = false]' at ../include/srsran/adt/optional.h:255:37,
    inlined from 'srsran::optional<std::__cxx11::basic_string<char> >::~optional()' at ../include/srsran/adt/optional.h:268:7,
    inlined from 'srsran::e1ap_cell_group_info_item::~e1ap_cell_group_info_item()' at ../include/srsran/e1ap/common/e1ap_types.h:66:8,
    inlined from 'void srsran::srs_cu_cp::fill_drb_to_setup_list(srsran::slotted_id_vector<srsran::drb_id_t, srsran::e1ap_drb_to_setup_item_ng_ran>&, const srsran::slotted_id_vector<srsran::qos_flow_id_t, qos_flow_setup_request_item>&, const std::map<srsran::drb_id_t, up_drb_context>&, const srslog::basic_logger&)' at ../lib/cu_cp/routines/pdu_session_routine_helpers.cpp:183:3:
/opt/rh/gcc-toolset-12/root/usr/include/c++/12/bits/basic_string.h:286:21: error: 'e1ap_cell_group_item.srsran::e1ap_cell_group_info_item::rat_type.srsran::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::storage.srsran::detail::optional_storage<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false, false, false>::<unnamed>.srsran::detail::optional_storage<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, true, false, false>::<unnamed>.srsran::detail::base_optional_storage<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::payload.srsran::detail::base_optional_storage<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::storage_type<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, false>::val.std::__cxx11::basic_string<char>::<anonymous>.std::__cxx11::basic_string<char>::<unnamed union>::_M_allocated_capacity' may be used uninitialized [-Werror=maybe-uninitialized]
  286 |           _M_destroy(_M_allocated_capacity);
      |           ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
../lib/cu_cp/routines/pdu_session_routine_helpers.cpp: In function 'void srsran::srs_cu_cp::fill_drb_to_setup_list(srsran::slotted_id_vector<srsran::drb_id_t, srsran::e1ap_drb_to_setup_item_ng_ran>&, const srsran::slotted_id_vector<srsran::qos_flow_id_t, qos_flow_setup_request_item>&, const std::map<srsran::drb_id_t, up_drb_context>&, const srslog::basic_logger&)':
../lib/cu_cp/routines/pdu_session_routine_helpers.cpp:172:31: note: 'e1ap_cell_group_item' declared here
  172 |     e1ap_cell_group_info_item e1ap_cell_group_item;
      |                               ^~~~~~~~~~~~~~~~~~~~